# Generated by Django 5.2 on 2025-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_userstudies_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('abstract', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstudies',
            name='annotated_studies',
        ),
        migrations.AddField(
            model_name='userstudies',
            name='favorite_studies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='docs.study'),
        ),
        migrations.AddField(
            model_name='userstudies',
            name='annotated_studies',
            field=models.ManyToManyField(blank=True, related_name='annotated_by', to='docs.study'),
        ),
    ]
